version: '3.8'
services:
  mysql_writer:
    build:
      context: .
      dockerfile: Dockerfile_writer
    container_name: mysql_writer
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: adjustment
    volumes:
      - ./mysql_writer_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my_network

  mysql_reader:
    build:
      context: .
      dockerfile: Dockerfile_reader
    container_name: mysql_reader
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: adjustment
    ports:
      - "3307:3306"
    networks:
      - my_network
    depends_on:
      - mysql_writer

networks:
  my_network:
    driver: bridge